spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_crud_hw_db
    password: Veronika73.
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true